spring:
  application:
    name: itoken-config
  zipkin:
    base-url: http://localhost:9411
  boot:
      admin:
        client:
          url: http://localhost:8084
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://gitee.com/fangyulong253711/springcloudconfig.git
          search-paths: fylconfig
          username: 15527142537
          password: fyl253711

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/