spring:
  application:
    name: itoken-web-admin
  boot:
    admin:
      client:
        url: http://localhost:8084
  zipkin:
    base-url: http://localhost:9411
  thymeleaf:
    cache: false #开发时关闭缓存，否则无法看到实时界面
    mode: LEGACYHTML #非严格的HTML
    encoding: UTF-8
    servlet:
      content-type: text/html

server:
  port: 8601

feign:
  hystrix:
    enable: true
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info